version: '3.9'

services:
  postgresql:
    image: postgres:alpine
    container_name: greenlight
    # command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
      # - ./ca/server.crt:/var/lib/postgresql/server.crt
      # - ./ca/server.key:/var/lib/postgresql/server.key
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
