version: '3.9'

services:
  postgresql:
    image: postgres:alpine
    container_name: greenlight
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
